# Generated by Django 3.2.7 on 2021-09-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_auto_20210901_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.RenameField(
            model_name='introducer',
            old_name='hire_fee',
            new_name='fee',
        ),
        migrations.RenameField(
            model_name='solicitor',
            old_name='ref',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='insurer',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='insurer',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='introducer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='introducer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='introducer',
            name='company_number',
        ),
        migrations.RemoveField(
            model_name='introducer',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='introducer',
            name='office_number',
        ),
        migrations.RemoveField(
            model_name='introducer',
            name='pi_fee',
        ),
        migrations.RemoveField(
            model_name='introducer',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='solicitor',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='solicitor',
            name='hotkey_number',
        ),
        migrations.RemoveField(
            model_name='solicitor',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='solicitor',
            name='pi_fee',
        ),
        migrations.AddField(
            model_name='insurer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='introducer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
