# Generated by Django 3.2.8 on 2021-11-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0008_auto_20211027_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='email',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
