# Generated by Django 3.2.8 on 2023-02-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0016_auto_20230225_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='postcode',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='postcode',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
