# Generated by Django 3.2.8 on 2023-02-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0018_piclient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PiClient',
        ),
    ]
