# Generated by Django 3.2.8 on 2023-02-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0020_piclient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PiClient',
        ),
    ]
