# Generated by Django 3.2.8 on 2023-02-28 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0086_remove_pidetail_client'),
        ('parties', '0022_piclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='piclient',
            name='pi_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.pidetail'),
        ),
    ]
