version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    &web
    image: "${WEB_IMAGE}"
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile.prod
      cache_from:
        - "${WEB_IMAGE}"
    command: gunicorn ccresponse.wsgi:application --bind 0.0.0.0:8000
    #volumes:
    #  - ./:/usr/src/app/
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - .env

  web_tasks_worker:
    <<: *web
    command: python manage.py run_huey

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/opt/redis/data

volumes:
  static_volume:
  redis-data: