# Generated by Django 3.1.6 on 2021-02-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210212_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='file',
            new_name='attachment',
        ),
        migrations.RenameField(
            model_name='injury',
            old_name='file',
            new_name='injury_file',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='file',
            new_name='invoice_file',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='file',
            new_name='template_file',
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
