# Generated by Django 3.1.6 on 2021-02-17 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210217_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='tp_other_details',
        ),
        migrations.RemoveField(
            model_name='case',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='solicitor',
            name='date_retained',
        ),
        migrations.RemoveField(
            model_name='solicitor',
            name='instruction_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='policy_number',
        ),
        migrations.AddField(
            model_name='case',
            name='customer_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_vehicle_cases', to='core.vehicle'),
        ),
        migrations.AddField(
            model_name='case',
            name='date_retained',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='instruction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_third_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_third_party_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='policy_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_purchased',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mot_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mot_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_purchased',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='service_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tax_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tax_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vrn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200)),
                ('other_details', models.TextField(blank=True)),
                ('insurer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurer_third_parties', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_third_parties', to='core.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Third parties',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='third_party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_party_cases', to='core.thirdparty'),
        ),
    ]
