# Generated by Django 3.1.6 on 2021-02-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_passwordresetrequest'),
        ('core', '0005_auto_20210217_1646'),
    ]

    operations = [
    ]
