# Generated by Django 3.1.6 on 2021-02-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210219_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introducer',
            name='externalpartyservice_ptr',
        ),
        migrations.RemoveField(
            model_name='solicitor',
            name='externalpartyservice_ptr',
        ),
        migrations.RemoveField(
            model_name='thirdparty',
            name='insurer',
        ),
        migrations.RemoveField(
            model_name='thirdparty',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='case',
            name='third_party',
        ),
        migrations.DeleteModel(
            name='Insurer',
        ),
        migrations.DeleteModel(
            name='Introducer',
        ),
        migrations.DeleteModel(
            name='Solicitor',
        ),
        migrations.DeleteModel(
            name='ThirdParty',
        ),
    ]
