# Generated by Django 3.1.6 on 2021-02-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210225_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='mot_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tax_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='mot_due',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='service_due',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='tax_due',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mot_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tax_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
