# Generated by Django 3.1.6 on 2021-02-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210227_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='mot_expiry',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='tax_expiry',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='service_due',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='tax_due',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='mot_due',
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mot_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tax_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
