# Generated by Django 3.1.7 on 2021-03-11 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210310_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='received_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_file',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='settlement_amount',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_third_party_vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='make_and_model',
        ),
        migrations.AddField(
            model_name='case',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_net_settled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_vat_settled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='daily_storage_rate',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=15),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.CharField(choices=[('customer', 'customer'), ('third party', 'third party'), ('company', 'company')], default='company', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='storage_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='storage_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='circumstances',
            field=models.CharField(blank=True, choices=[('tired', 'Tired'), ('sleepy', 'Sleepy'), ('rainy', 'Rainy')], max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('waiting', 'Waiting')], max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('payment_pack', 'Payment Pack'), ('settled', 'Settled'), ('rejected', 'Rejected')], default='ongoing', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(max_length=100),
        ),
    ]
