# Generated by Django 3.1.7 on 2021-03-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210311_2026'),
        ('core', '0015_auto_20210312_1146'),
    ]

    operations = [
    ]
