# Generated by Django 3.1.7 on 2021-03-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20210314_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('payment_pack', 'Payment Pack'), ('settled', 'Settled'), ('rejected', 'Rejected')], default='ongoing', max_length=30),
        ),
    ]
