# Generated by Django 3.1.7 on 2021-03-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210316_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.CharField(choices=[('customer', 'Customer'), ('third_party', 'Third Party'), ('company', 'Company')], default='company', max_length=20),
        ),
    ]
