# Generated by Django 3.1.7 on 2021-03-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210319_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledToChaseCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chase_date', models.DateField()),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.case')),
            ],
        ),
    ]
