# Generated by Django 3.1.7 on 2021-03-26 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210326_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='storage_end_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='storage_start_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='vehicle_hire',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='core.vehiclehire'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vehicle_recovery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='core.vehiclerecovery'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vehicle_storage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='core.vehiclestorage'),
        ),
    ]
