# Generated by Django 3.1.7 on 2021-03-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210326_1536'),
        ('core', '0022_auto_20210329_1353'),
    ]

    operations = [
    ]
