# Generated by Django 3.1.7 on 2021-03-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210329_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total_net_settled',
            new_name='settled_amount_net',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='total_vat_settled',
            new_name='settled_amount_vat',
        ),
        migrations.AddField(
            model_name='invoice',
            name='settled_amount_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
