# Generated by Django 3.1.7 on 2021-04-06 13:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210331_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclehire',
            name='add_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='auto_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=15),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='bluetooth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='bluetooth_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=15),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.case'),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='clear_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='collection_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=15),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='cwd_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('12'), max_digits=15),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='cwd_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=15),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='driver_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=15),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='ns_drive_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='outsourced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='sat_nav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='sat_nav_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=15),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='towbar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='towbar_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=15),
        ),
        migrations.AddField(
            model_name='vehiclerecovery',
            name='call_out_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerecovery',
            name='inherited_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerecovery',
            name='recovery_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerecovery',
            name='road_cleanup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclerecovery',
            name='skates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclerecovery',
            name='winching_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclestorage',
            name='engineers_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vrn',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='VehicleHireValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engs_instructed_date', models.DateField(blank=True, null=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('report_received_date', models.DateField(blank=True, null=True)),
                ('send_to_tp_date', models.DateField(blank=True, null=True)),
                ('repairable', models.BooleanField(default=True)),
                ('total_loss_cil', models.BooleanField(default=True)),
                ('settle_offer', models.BooleanField(default=False)),
                ('offer_accepted', models.BooleanField(default=False)),
                ('cheque_received', models.BooleanField(default=False)),
                ('liability_admitted', models.BooleanField(default=False)),
                ('vehicle_hire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hire_validation', to='core.vehiclehire')),
            ],
        ),
    ]
