# Generated by Django 3.1.7 on 2021-04-08 09:02

import ccresponse.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210407_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocument',
            name='file',
            field=models.FileField(storage=ccresponse.storage_backends.PrivateMediaStorage(), upload_to='case_documents'),
        ),
    ]
