# Generated by Django 3.1.7 on 2021-04-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210408_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocument',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
