# Generated by Django 3.1.7 on 2021-04-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210408_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclehire',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hires', to='core.case'),
        ),
    ]
