# Generated by Django 3.1.7 on 2021-04-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210408_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='title',
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
