# Generated by Django 3.2 on 2021-05-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_case_should_show_hire_sr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclestorage',
            name='engineers_fee',
        ),
        migrations.AddField(
            model_name='vehiclerecovery',
            name='date_repair_authorized',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerecovery',
            name='date_satisfaction_note_signed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerecovery',
            name='engineers_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
