# Generated by Django 3.2 on 2021-05-07 17:00

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20210507_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='thirdparty',
            name='address',
        ),
    ]
