# Generated by Django 3.2 on 2021-05-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20210507_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address_obj',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='thirdparty',
            old_name='address_obj',
            new_name='address',
        ),
    ]
