# Generated by Django 3.2.6 on 2021-08-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20210728_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructEngineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Instruct engineer',
            },
        ),
    ]
