# Generated by Django 3.2.8 on 2021-11-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20211021_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructengineer',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='party',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(error_messages={'unique': 'A user with that email already exists.'}, max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
