# Generated by Django 3.2.7 on 2021-09-28 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0030_auto_20210919_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('charge_type', models.CharField(choices=[('hire', 'Hire'), ('storage_and_recovery', 'Storage/Recovery')], max_length=20)),
                ('total_net', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('settlement_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='cases.case')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
