# Generated by Django 3.2.7 on 2021-10-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_net',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_vat',
        ),
    ]
