# Generated by Django 3.2.8 on 2021-11-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0056_hirevalidation_liability_admitted'),
        ('invoices', '0005_auto_20211126_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='hire_invoice_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='hire_invoice_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='last_invoice_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='recovery_invoice_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='recovery_invoice_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='storage_invoice_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='storage_invoice_total',
        ),
        migrations.AddField(
            model_name='invoice',
            name='charge_type',
            field=models.CharField(choices=[('hire', 'Hire'), ('storage_and_recovery', 'Storage/Recovery')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='settlement_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hire_invoice_date', models.DateField(blank=True, null=True)),
                ('hire_invoice_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('storage_invoice_date', models.DateField(blank=True, null=True)),
                ('storage_invoice_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('recovery_invoice_date', models.DateField(blank=True, null=True)),
                ('recovery_invoice_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_invoice_date', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_files', to='cases.case')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
