# Generated by Django 3.2.8 on 2021-12-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20211126_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairinvoice',
            name='labour_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='repairinvoice',
            name='labour_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
