# Generated by Django 3.2.5 on 2021-07-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accident_date', models.DateField(blank=True, null=True)),
                ('approx_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('circumstances', models.CharField(blank=True, choices=[('tired', 'Tired'), ('sleepy', 'Sleepy'), ('rainy', 'Rainy')], max_length=50, null=True)),
                ('weather', models.CharField(max_length=255)),
                ('other_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Accident',
                'verbose_name_plural': 'Accidents',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('payment_pack', 'Payment Pack'), ('settled', 'Settled')], default='ongoing', max_length=50)),
                ('payment_status', models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('waiting', 'Waiting')], max_length=50, null=True)),
                ('instruction_date', models.DateField(blank=True, null=True)),
                ('retained_date', models.DateField(blank=True, null=True)),
                ('communication', models.TextField(blank=True, null=True)),
                ('ack_comms', models.BooleanField(default=False)),
                ('accident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.accident')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='parties.client')),
                ('third_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parties.thirdparty')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
            },
        ),
    ]
