# Generated by Django 3.2.5 on 2021-07-20 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_auto_20210720_1706'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='introducer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.introducer'),
        ),
        migrations.AddField(
            model_name='case',
            name='solicitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.solicitor'),
        ),
        migrations.AlterField(
            model_name='case',
            name='accident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.accident'),
        ),
        migrations.AlterField(
            model_name='case',
            name='third_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.thirdparty'),
        ),
    ]
