# Generated by Django 3.2.5 on 2021-07-28 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20210720_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClawbackDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('replace_name', models.CharField(blank=True, max_length=127, null=True)),
                ('intro_rep_case', models.DateField(blank=True, null=True)),
                ('we_rep_case', models.DateField(blank=True, null=True)),
                ('chase_date', models.DateField(blank=True, null=True)),
                ('replaced', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HireDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('outsourced', models.BooleanField(default=False)),
                ('charge', models.PositiveIntegerField(blank=True, null=True)),
                ('collection', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('cdw_required', models.BooleanField(default=False)),
                ('cdw', models.PositiveIntegerField(blank=True, null=True)),
                ('add_driver', models.BooleanField(default=False)),
                ('sat_nav', models.BooleanField(default=False)),
                ('auto', models.BooleanField(default=False)),
                ('towbar', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('ns_drive_charge', models.PositiveIntegerField(blank=True, null=True)),
                ('engs_instructed', models.DateField(blank=True, null=True)),
                ('report_received', models.DateField(blank=True, null=True)),
                ('sent_to_tp', models.DateField(blank=True, null=True)),
                ('tp_auth_received', models.DateField(blank=True, null=True)),
                ('booking_in_date', models.DateField(blank=True, null=True)),
                ('repairs_started', models.DateField(blank=True, null=True)),
                ('est_completion_date', models.DateField(blank=True, null=True)),
                ('act_completion', models.DateField(blank=True, null=True)),
                ('returned_to_customer', models.DateField(blank=True, null=True)),
                ('rep_inv_amt', models.PositiveIntegerField(blank=True, null=True)),
                ('rep_inv_vat', models.PositiveIntegerField(blank=True, null=True)),
                ('rep_cost_outlay', models.PositiveIntegerField(blank=True, null=True)),
                ('rep_pay_received', models.DateField(blank=True, null=True)),
                ('liability_admitted', models.BooleanField(default=False)),
                ('settlement_status', models.CharField(blank=True, choices=[('with_cc_response', 'With CC Response'), ('with_solicitor_stage_two', 'With Solicitor - Stage 2'), ('with_solicitor_issued', 'With Solicitor - Issued'), ('settlement_agreed', 'Settlement Agreed'), ('settlement_received', 'Settlement Received')], max_length=50, null=True)),
                ('hire_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('recovery_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('engineers_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('global_settlement', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='case',
            name='clawback_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.clawbackdetail'),
        ),
        migrations.AddField(
            model_name='case',
            name='hire_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.hiredetail'),
        ),
    ]
