# Generated by Django 3.2.5 on 2021-08-06 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20210802_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='follow_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.followup'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='weather',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
