# Generated by Django 3.2.5 on 2021-08-06 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_auto_20210806_1103'),
        ('cases', '0006_auto_20210806_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='parties.client'),
        ),
    ]
