# Generated by Django 3.2.5 on 2021-08-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_case_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at'], 'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
    ]
