# Generated by Django 3.2.6 on 2021-08-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_userdisplaycasecolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('payment_pack', 'Payment Pack'), ('settled', 'Settled')], default='ongoing', max_length=50),
        ),
    ]
