# Generated by Django 3.2.6 on 2021-08-21 14:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdisplaycasecolumn',
            name='columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('instruction_date', 'Instruction date'), ('accident_date', 'Accident date'), ('client_name', 'Client name'), ('phone_number', 'Phone number'), ('introducer', 'Introducer'), ('instructed_solicitor', 'Instructed solicitor'), ('tp_insurer', 'Third party insurer')], max_length=20), default=list, size=7),
        ),
    ]
