# Generated by Django 3.2.6 on 2021-08-23 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_expense'),
        ('cases', '0013_alter_userdisplaycasecolumn_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiredetail',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='hiredetail',
            name='hire_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hire_details', to='vehicles.hirevehicle'),
        ),
    ]
