# Generated by Django 3.2.6 on 2021-08-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_auto_20210823_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiredetail',
            old_name='hire_vehicle',
            new_name='vehicle',
        ),
    ]
