# Generated by Django 3.2.6 on 2021-08-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_casenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('lead', 'Lead'), ('ongoing', 'Ongoing'), ('payment_pack', 'Payment Pack'), ('settled', 'Settled'), ('closed', 'Closed')], default='ongoing', max_length=50),
        ),
    ]
