# Generated by Django 3.2.6 on 2021-08-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_auto_20210825_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedetail',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
