# Generated by Django 3.2.6 on 2021-08-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_storagedetail_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pidetail',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=50),
        ),
    ]
