# Generated by Django 3.2.6 on 2021-08-29 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_auto_20210812_1558'),
        ('cases', '0020_alter_pidetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='accident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.accident'),
        ),
        migrations.AlterField(
            model_name='case',
            name='clawback_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.clawbackdetail'),
        ),
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='parties.client'),
        ),
        migrations.AlterField(
            model_name='case',
            name='hire_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.hiredetail'),
        ),
        migrations.AlterField(
            model_name='case',
            name='introducer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.introducer'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pi_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.pidetail'),
        ),
        migrations.AlterField(
            model_name='case',
            name='recovery_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.recoverydetail'),
        ),
        migrations.AlterField(
            model_name='case',
            name='solicitor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.solicitor'),
        ),
        migrations.AlterField(
            model_name='case',
            name='storage_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.storagedetail'),
        ),
        migrations.AlterField(
            model_name='case',
            name='third_party',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.thirdparty'),
        ),
    ]
