# Generated by Django 3.2.6 on 2021-09-01 07:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_auto_20210812_1558'),
        ('cases', '0022_alter_pidetail_claim_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='introducer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.introducer'),
        ),
        migrations.AlterField(
            model_name='case',
            name='solicitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.solicitor'),
        ),
        migrations.AlterField(
            model_name='pidetail',
            name='claim_num',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
