# Generated by Django 3.2.6 on 2021-09-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_auto_20210901_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('lead', 'Lead'), ('ongoing', 'Ongoing'), ('payment_pack', 'Payment Pack'), ('settled', 'Settled'), ('closed', 'Closed')], default='lead', max_length=50),
        ),
    ]
