# Generated by Django 3.2.6 on 2021-09-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='solicitor_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
