# Generated by Django 3.2.6 on 2021-09-02 14:08

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_case_solicitor_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFieldsDefaultPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_detail_call_out_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('recovery_detail_inherited_fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('storage_detail_fee_per_day', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('storage_detail_engineers_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('hire_detail_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('hire_detail_cdw', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('hire_detail_ns_drive_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('hire_detail_rep_inv_amt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('hire_detail_rep_inv_vat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('hire_detail_rep_cost_outlay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('hire_detail_hire_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('hire_detail_recovery_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('hire_detail_engineers_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('hire_detail_storage_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Case fields default price',
            },
        ),
    ]
