# Generated by Django 3.2.6 on 2021-09-06 05:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_alter_case_instruction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='instruction_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
