# Generated by Django 3.2.7 on 2021-09-16 12:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0028_alter_case_instruction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_charge',
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_add_driver',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_auto',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_bluetooth',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_collection',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_delivery',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_sat_nav',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_towbar',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='recovery_detail_road_cleanup',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_cdw',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=12),
        ),
    ]
