# Generated by Django 3.2.7 on 2021-09-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cases', '0030_auto_20210919_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiredetail',
            name='add_driver',
        ),
        migrations.AddField(
            model_name='hiredetail',
            name='add_driver',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RemoveField(
            model_name='hiredetail',
            name='auto',
        ),
        migrations.AddField(
            model_name='hiredetail',
            name='auto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RemoveField(
            model_name='hiredetail',
            name='bluetooth',
        ),
        migrations.AddField(
            model_name='hiredetail',
            name='bluetooth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RemoveField(
            model_name='hiredetail',
            name='collection',
        ),
        migrations.AddField(
            model_name='hiredetail',
            name='collection',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RemoveField(
            model_name='hiredetail',
            name='delivery',
        ),
        migrations.AddField(
            model_name='hiredetail',
            name='delivery',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RemoveField(
            model_name='hiredetail',
            name='sat_nav',
        ),
        migrations.AddField(
            model_name='hiredetail',
            name='sat_nav',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RemoveField(
            model_name='hiredetail',
            name='towbar',
        ),
        migrations.AddField(
            model_name='hiredetail',
            name='towbar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RemoveField(
            model_name='recoverydetail',
            name='road_cleanup',
        ),
        migrations.AddField(
            model_name='recoverydetail',
            name='road_cleanup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
