# Generated by Django 3.2.7 on 2021-10-06 11:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_auto_20210928_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='recovery_detail_hour_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('90'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='recovery_detail_minutes_30',
            field=models.DecimalField(decimal_places=2, default=Decimal('45'), max_digits=12),
        ),
    ]
