# Generated by Django 3.2.7 on 2021-10-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0032_auto_20211006_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='instruct_engineer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
