# Generated by Django 3.2.7 on 2021-10-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0034_auto_20211010_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='introducer_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
