# Generated by Django 3.2.7 on 2021-10-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0035_case_introducer_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiredetail',
            old_name='add_driver',
            new_name='driver_fee',
        ),
        migrations.AddField(
            model_name='hiredetail',
            name='driver_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiredetail',
            name='driver_full_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hiredetail',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hiredetail',
            name='driver_required',
            field=models.BooleanField(default=False),
        ),
    ]
