# Generated by Django 3.2.7 on 2021-10-14 05:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0037_auto_20211014_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_one_fee_for_skates',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='recoverydetail',
            name='skates',
            field=models.CharField(blank=True, choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5, null=True),
        ),
    ]
