# Generated by Django 3.2.7 on 2021-10-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0038_auto_20211014_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiredetail',
            old_name='ns_drive_charge',
            new_name='ns_driver_fee',
        ),
        migrations.AddField(
            model_name='hiredetail',
            name='ns_drive_reason',
            field=models.CharField(blank=True, choices=[('age', 'Age (under 25 or older than 70)'), ('occupation', 'Occupation'), ('driving_licence', 'Held a full driving licence in the UK for less than 12 months'), ('convictions_points', 'Convictions/points')], max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='hiredetail',
            name='ns_driver_surcharge',
            field=models.BooleanField(default=False),
        ),
    ]
