# Generated by Django 3.2.7 on 2021-10-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0039_auto_20211014_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiredetail',
            old_name='ns_drive_reason',
            new_name='ns_driver_reason',
        ),
    ]
