# Generated by Django 3.2.7 on 2021-10-17 16:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0040_rename_ns_drive_reason_hiredetail_ns_driver_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdisplaycasecolumn',
            name='columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('cc_ref', 'CC Ref'), ('instruction_date', 'Instruction date'), ('accident_date', 'Accident date'), ('client_name', 'Client name'), ('phone_number', 'Phone number'), ('introducer', 'Introducer'), ('provider', 'Provider'), ('instructed_solicitor', 'Instructed solicitor'), ('tp_insurer', 'Third party insurer')], max_length=20), default=list, size=8),
        ),
    ]
