# Generated by Django 3.2.7 on 2021-10-21 09:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0042_alter_casefieldsdefaultprice_recovery_detail_road_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_add_driver',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_auto',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_bluetooth',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_cdw',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_collection',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_delivery',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_one_fee_for_skates',
            field=models.DecimalField(decimal_places=2, default=Decimal('25'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_sat_nav',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='casefieldsdefaultprice',
            name='hire_detail_towbar',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='casefieldsdefaultprice',
            name='recovery_detail_road_cleanup',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='casefieldsdefaultprice',
            name='storage_detail_engineers_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('125'), max_digits=12),
        ),
    ]
