# Generated by Django 3.2.8 on 2021-11-09 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0044_alter_userdisplaycasecolumn_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='instruction_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
