# Generated by Django 3.2.8 on 2021-11-23 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0049_alter_case_status_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('outsourced_to', models.CharField(blank=True, choices=[('spectra', 'Spectra'), ('winn', 'WINN'), ('blackthorn', 'Blackthorn'), ('dwa', 'DWA')], max_length=32, null=True)),
                ('repair_status', models.CharField(blank=True, choices=[('repairable', 'Repairable'), ('total_loss', 'Total loss')], max_length=32, null=True)),
                ('hire_ref_fee', models.CharField(blank=True, choices=[('na', 'N/A'), ('450', '£450'), ('500', '£500'), ('750', '£750')], max_length=3, null=True)),
                ('repair_ref_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salvage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sold_via', models.CharField(blank=True, choices=[('copart', 'Copart'), ('ebay', 'Ebay'), ('other', 'Other')], max_length=16, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HireAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('offer_received', models.CharField(blank=True, choices=[('received', 'Received'), ('not_received', 'Not received')], max_length=32, null=True)),
                ('personally_liable', models.BooleanField(blank=True, default=False, null=True)),
                ('vehicle_unroadworthy', models.BooleanField(blank=True, default=False, null=True)),
                ('no_another_vehicle', models.BooleanField(blank=True, default=False, null=True)),
                ('hire_reason', models.TextField(blank=True, null=True)),
                ('prosecution', models.BooleanField(blank=True, default=False, null=True)),
                ('accident_loss_in_3_past_years', models.BooleanField(blank=True, default=False, null=True)),
                ('proposal_declined_or_increased_fees', models.BooleanField(blank=True, default=False, null=True)),
                ('diseases', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='accident',
            name='circumstances',
            field=models.CharField(blank=True, choices=[('hir', 'HIR'), ('tp_pulled_from_sr', 'TP pulled from SR'), ('roundabout_accident', 'Roundabout accident'), ('lane_change', 'Lane change'), ('tp_pulled_from_parked_position', 'TP pulled from parked position'), ('reversing_accident', 'Reversing accident'), ('car_park_accident', 'Car park accident'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_fee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.casefee'),
        ),
        migrations.AddField(
            model_name='case',
            name='hire_agreement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.hireagreement'),
        ),
    ]
