# Generated by Django 3.2.8 on 2021-11-24 11:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0052_case_repair_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='repair_invoice_anti_corrosion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='repair_invoice_car_kit_and_mini_valet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='repair_invoice_covid_clean_and_ppe',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='repair_invoice_epa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='repair_invoice_geometry',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='repair_invoice_miscellaneous_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='repair_invoice_paint_and_sundries',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='repair_invoice_parts_mlp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='repair_invoice_remove_and_refit_glass',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='casefieldsdefaultprice',
            name='repair_invoice_specialist_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
