# Generated by Django 3.2.8 on 2021-11-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0053_auto_20211124_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pidetail',
            name='claim_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
