# Generated by Django 3.2.8 on 2021-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0054_alter_pidetail_claim_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirevalidation',
            name='liability_admitted',
        ),
        migrations.AddField(
            model_name='hirevalidation',
            name='liability_admitted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
