# Generated by Django 3.2.8 on 2021-11-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0055_auto_20211125_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirevalidation',
            name='liability_admitted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
