# Generated by Django 3.2.8 on 2021-12-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0057_case_recovery_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='approx_time',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
