# Generated by Django 3.2.8 on 2022-01-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0060_alter_userdisplaycasecolumn_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoverydetail',
            name='road_cleanup',
        ),
        migrations.AddField(
            model_name='recoverydetail',
            name='road_cleanup',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
