# Generated by Django 3.2.8 on 2022-01-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0061_alter_recoverydetail_road_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverydetail',
            name='recovery_type',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('out_of_hours', 'Out of hours'), ('would_not_drive_steer_roll', 'Would not drive/Steer/Roll'), ('crane_four_wheel_lift_required', 'Crane/Four wheel lift required'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
