# Generated by Django 3.2.8 on 2023-02-27 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0065_auto_20230226_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredetail',
            name='service_provider',
            field=models.CharField(blank=True, choices=[('ccr', 'CCR'), ('europcar', 'Europcar'), ('winn', 'WINN'), ('erac', 'ERAC'), ('spectra', 'Spectra'), ('strada', 'Strada')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='file_handler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_handler', to=settings.AUTH_USER_MODEL),
        ),
    ]
