# Generated by Django 3.2.8 on 2023-02-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0070_storagedetail_provider_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredetail',
            name='abi_cat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
