# Generated by Django 3.2.8 on 2023-02-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0072_remove_hiredetail_abi_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredetail',
            name='abi_cat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hiredetail',
            name='make_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
