# Generated by Django 3.2.8 on 2023-02-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0073_auto_20230227_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredetail',
            name='category',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('prestige', 'Prestige'), ('taxi', 'Taxi')], max_length=20, null=True),
        ),
    ]
