# Generated by Django 3.2.8 on 2023-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0074_hiredetail_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiredetail',
            name='status',
            field=models.CharField(blank=True, choices=[('hire_arranged', 'Hire Arranged'), ('in_hire', 'In Hire'), ('hire_ended', 'Hire ended'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
