# Generated by Django 3.2.8 on 2023-02-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0075_alter_hiredetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredetail',
            name='outsourced_vehicle_fee',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('prestige', 'Prestige')], max_length=20, null=True),
        ),
    ]
