# Generated by Django 3.2.8 on 2023-02-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0078_alter_hiredetail_outsourced_vehicle_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiredetail',
            name='outsourced_vehicle_fee',
            field=models.CharField(blank=True, choices=[('400.00', 'Standard'), ('650.00', 'Prestige')], max_length=12, null=True),
        ),
    ]
