# Generated by Django 3.2.8 on 2023-02-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0079_alter_hiredetail_outsourced_vehicle_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiredetail',
            old_name='category',
            new_name='hire_categories',
        ),
    ]
