# Generated by Django 3.2.8 on 2023-02-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0080_rename_category_hiredetail_hire_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidetail',
            name='pi_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('paid', 'Paid')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pidetail',
            name='provider',
            field=models.CharField(blank=True, choices=[('winn', 'WINN'), ('easidrive', 'Easidrive'), ('dgm', 'DGM'), ('thompsons', 'Thompsons')], max_length=20, null=True),
        ),
    ]
