# Generated by Django 3.2.8 on 2023-02-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0082_auto_20230228_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pidetail',
            name='client',
        ),
        migrations.DeleteModel(
            name='PiClient',
        ),
    ]
