# Generated by Django 3.2.8 on 2023-02-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0022_piclient'),
        ('cases', '0084_auto_20230228_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pidetail',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.piclient'),
        ),
        migrations.DeleteModel(
            name='PiClient',
        ),
    ]
