# Generated by Django 3.2.8 on 2023-03-02 08:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0086_remove_pidetail_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=['claim'], size=6),
        ),
    ]
