# Generated by Django 3.2.8 on 2023-03-02 09:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0087_case_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('cd', 'Claim Details'), ('hd', 'Hire Details'), ('sr', 'Storage Recovery'), ('pi', 'Personal Injury'), ('vd', 'Vehicle Damage'), ('sv', 'Salvage')], max_length=20), default=['cd'], size=6),
        ),
    ]
