# Generated by Django 3.2.8 on 2023-03-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0089_remove_hiredetail_make_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='casenote',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casenote',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casenote',
            name='type',
            field=models.CharField(choices=[('note', 'Note'), ('task', 'Task')], default='note', max_length=55),
        ),
    ]
