# Generated by Django 3.2.8 on 2023-05-31 17:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0092_auto_20230323_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('cd', 'Claim Details'), ('hd', 'Hire Details'), ('sr', 'Storage Recovery'), ('pi', 'Personal Injury'), ('vd', 'Vehicle Damage'), ('sv', 'Salvage')], max_length=20), default=['cd', 'hd', 'sr', 'pi', 'vd', 'sr'], size=6),
        ),
    ]
