# Generated by Django 3.2.8 on 2023-06-19 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0094_auto_20230612_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='hire_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.hiredetail'),
        ),
    ]
