# Generated by Django 3.2.8 on 2021-11-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0045_alter_case_instruction_date'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='case',
        ),
        migrations.AddField(
            model_name='notification',
            name='cases',
            field=models.ManyToManyField(to='cases.Case'),
        ),
    ]
