# Generated by Django 3.2.8 on 2021-11-17 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0045_alter_case_instruction_date'),
        ('notification', '0002_auto_20211117_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='cases',
        ),
        migrations.AddField(
            model_name='notification',
            name='case',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='cases.case'),
            preserve_default=False,
        ),
    ]
