# Generated by Django 3.2.7 on 2021-09-16 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0028_alter_case_instruction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.CharField(choices=[('client', 'Client'), ('manager', 'Manager')], max_length=7)),
                ('source', models.CharField(choices=[('crm', 'CRM'), ('whatsapp', 'WhatsApp')], max_length=8)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File')], max_length=5)),
                ('content', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=512, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='cases.case')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
