# Generated by Django 3.2.7 on 2021-09-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='pre_signed_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='pre_signed_url_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['case'], name='chat_chatme_case_id_899d01_idx'),
        ),
    ]
