# Generated by Django 3.2.7 on 2021-09-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210920_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
