# Generated by Django 3.2.7 on 2021-09-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='whats_app_chat_status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('pending', 'Pending'), ('active', 'Active')], default='inactive', max_length=8),
        ),
    ]
