# Generated by Django 3.2.7 on 2021-09-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chat_whats_app_chat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='twilio_message_status',
            field=models.CharField(blank=True, choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('received', 'Received'), ('read', 'Read')], max_length=9, null=True),
        ),
    ]
