# Generated by Django 3.2.8 on 2023-06-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_time_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='last_run_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
