# Generated by Django 3.2.8 on 2023-06-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_last_run_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time_frequency',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='time_unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], max_length=10),
        ),
    ]
