# Generated by Django 3.2.8 on 2023-08-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20230615_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='has_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='time_unit',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10),
        ),
    ]
