# Generated by Django 3.2.6 on 2021-09-07 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ccresponse.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0028_alter_case_instruction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseUploadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(storage=ccresponse.storage_backends.PrivateMediaStorage(), upload_to='case_documents')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_documents', to='cases.case')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case document',
                'verbose_name_plural': 'Case documents',
            },
        ),
    ]
