# Generated by Django 3.2.6 on 2021-09-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_caseuploaddocument_empty_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseuploaddocument',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
    ]
