# Generated by Django 3.2.7 on 2021-09-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_caseuploaddocument_is_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sender', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('created', 'Created'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('signed', 'Signed'), ('completed', 'Completed'), ('declined', 'Declined'), ('voided', 'Voided'), ('deleted', 'Deleted')], max_length=9, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.caseuploaddocument')),
            ],
            options={
                'verbose_name': 'Case document',
                'verbose_name_plural': 'Case documents',
            },
        ),
    ]
