# Generated by Django 3.2.7 on 2021-09-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_documentsignature_envelope_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseuploaddocument',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
