# Generated by Django 3.2.7 on 2021-10-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_caseuploaddocument_is_to_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseuploaddocument',
            name='document_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
