# Generated by Django 3.2.7 on 2021-10-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_caseuploaddocument_document_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsignature',
            name='document',
        ),
        migrations.DeleteModel(
            name='CaseUploadDocument',
        ),
        migrations.DeleteModel(
            name='DocumentSignature',
        ),
    ]
