# Generated by Django 3.2.7 on 2021-10-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20211017_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(max_length=127)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('signed', 'Signed'), ('completed', 'Completed'), ('declined', 'Declined'), ('voided', 'Voided'), ('deleted', 'Deleted')], default='created', max_length=9)),
                ('envelope_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_signature', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document signature',
                'verbose_name_plural': 'Document signatures',
            },
        ),
    ]
