# Generated by Django 3.2.8 on 2021-10-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_documenttemplates_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplates',
            name='template_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
