# Generated by Django 3.2.8 on 2021-10-27 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0044_alter_userdisplaycasecolumn_columns'),
        ('parties', '0008_auto_20211027_0625'),
        ('documents', '0016_alter_documenttemplates_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='introducer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parties.introducer'),
        ),
        migrations.AddField(
            model_name='document',
            name='solicitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parties.solicitor'),
        ),
        migrations.AlterField(
            model_name='document',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
