# Generated by Django 3.2.5 on 2021-07-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vrn', models.CharField(blank=True, max_length=127, null=True)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('mot_expiry', models.DateField(blank=True, null=True)),
                ('tax_expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client vehicle',
                'verbose_name_plural': 'Client vehicles',
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vrn', models.CharField(blank=True, max_length=127, null=True)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('mot_expiry', models.DateField(blank=True, null=True)),
                ('tax_expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Third party vehicle',
                'verbose_name_plural': 'Third party vehicles',
            },
        ),
    ]
