# Generated by Django 3.2.5 on 2021-08-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientvehicle',
            old_name='make',
            new_name='make_model',
        ),
        migrations.RenameField(
            model_name='thirdpartyvehicle',
            old_name='make',
            new_name='make_model',
        ),
        migrations.RemoveField(
            model_name='clientvehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='thirdpartyvehicle',
            name='model',
        ),
    ]
