# Generated by Django 3.2.5 on 2021-08-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20210803_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvehicle',
            name='make_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdpartyvehicle',
            name='make_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
