# Generated by Django 3.2.6 on 2021-08-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20210806_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vrn', models.CharField(blank=True, max_length=127, null=True)),
                ('make_model', models.CharField(blank=True, max_length=255, null=True)),
                ('mot_expiry', models.DateField(blank=True, null=True)),
                ('tax_expiry', models.DateField(blank=True, null=True)),
                ('registration', models.CharField(blank=True, max_length=127, null=True)),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('service_due', models.DateField(blank=True, null=True)),
                ('tax_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mot_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_sold', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Hire vehicle',
                'verbose_name_plural': 'Hire vehicles',
            },
        ),
    ]
