# Generated by Django 3.2.6 on 2021-09-02 14:08

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleFieldsDefaultPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_vehicle_purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('hire_vehicle_tax_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('hire_vehicle_mot_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('expense_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Vehicle fields default price',
            },
        ),
    ]
