# Generated by Django 3.2.8 on 2023-02-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehiclefieldsdefaultprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvehicle',
            name='make_model',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientvehicle',
            name='mot_expiry',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientvehicle',
            name='tax_expiry',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientvehicle',
            name='vrn',
            field=models.CharField(blank=True, db_index=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='hirevehicle',
            name='date_purchased',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hirevehicle',
            name='make_model',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hirevehicle',
            name='mot_cost',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='hirevehicle',
            name='mot_expiry',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hirevehicle',
            name='notes',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hirevehicle',
            name='purchase_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='hirevehicle',
            name='registration',
            field=models.CharField(blank=True, db_index=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='hirevehicle',
            name='service_due',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hirevehicle',
            name='tax_cost',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='hirevehicle',
            name='tax_expiry',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hirevehicle',
            name='vrn',
            field=models.CharField(blank=True, db_index=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='thirdpartyvehicle',
            name='make_model',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdpartyvehicle',
            name='mot_expiry',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdpartyvehicle',
            name='tax_expiry',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdpartyvehicle',
            name='vrn',
            field=models.CharField(blank=True, db_index=True, max_length=127, null=True),
        ),
    ]
