# Generated by Django 3.2.8 on 2023-02-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20230225_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirevehicle',
            name='abi_cat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
